apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs
  template:
    metadata:
      labels:
        app: open5gs
    spec:
      containers:
      - name: open5gs
        image: open5gs-core
