name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install Docker
    #- name: Install Docker
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y docker.io

    # Build Docker image
    - name: Build Image
      run: docker build -t open5gs-core .

    # Install kubectl
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    # Install KIND
    - name: Install KIND
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    # Create cluster
    - name: Create Cluster
      run: kind create cluster

    # Load image
    - name: Load Image
      run: kind load docker-image open5gs-core

    # Deploy
    - name: Deploy
      run: kubectl apply -f k8s/

    # Debug
    - name: Debug Pods
      run: kubectl get pods -o wide

    # Wait
    - name: Wait
      run: sleep 15

    # Test
    - name: Test
      run: |
        kubectl get pods
        if kubectl get pods | grep -q Running
        then
          echo "PASS ✅"
        else
          echo "FAIL ❌"
          exit 1
        fi
